import Head from 'next/head'
import Header from './components/header'
import Footer from './components/footer'
import Landing from './components/landing'
import About from './components/about'
import Service from './components/service'
import Project from './components/project'
import Testimonial from './components/testimonial'

export default function Home() {
  // const trailer = document.getElementById('trailer');

  // window.onmousemove = e => {
  //   const x = e.clientX - trailer.offsetWidth / 2,
  //         y = e.clientY - trailer.offsetHeight / 2;

  //   const keyframes = {
  //     transform: `translate(${x}px, ${y}px)`
  //   }

  //   trailer.animate(keyframes, {
  //     duration: 800,
  //     fill: "forwards"
  //   })
  // }

  return (
    <div>
      <Head>
        <title>Picowind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id="trailer" />
        <Header />
        <Landing />
        <About />
        <Service />
        <Project />
        <Testimonial />
        <Footer />
      </main>
    </div>
  )
}
