import Head from 'next/head'
import Header from './components/header'
import Footer from './components/footer'
import Landing from './components/landing'
import About from './components/about'
import Service from './components/service'
import Project from './components/project'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Picowind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Landing />
        <About />
        <Service />
        <Project />
        <Footer />
      </main>
    </div>
  )
}
